trigger: none
pool: test-pool
jobs:
 - job: tflint
   displayName: terraform tf lint
   steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd $(System.DefaultWorkingDirectory)/terraform
          tflint --init
          tflint --recursive

 - job: terraforminit 
   displayName: terraform init
   steps:
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
         backendServiceArm: 'todo-sec-svc'
         backendAzureRmStorageAccountName: 'sandisk11'
         backendAzureRmContainerName: 'friday11'
         backendAzureRmKey: 'prod.terraform.tfstate'
     - task: PublishPipelineArtifact@1
       inputs:
         targetPath: '$(System.DefaultWorkingDirectory)/terraform'
         artifact: 'tf-config'
         publishLocation: 'pipeline'
 - job: terraformplan
   dependsOn: terraforminit
   displayName: 
   steps:
     - task: DownloadPipelineArtifact@2
       inputs:
         buildType: 'current'
         artifactName: 'tf-config'
         targetPath: '$(Pipeline.Workspace)'
     - task: Bash@3
       inputs:
         targetType: 'inline'
         script: |
           cd $(Pipeline.Workspace)/terraform
           chmod -R a+rwX .terraform/providers
           chmod -R a+rwX .terraform.lock.hcl
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         workingDirectory: '$(Pipeline.Workspace)/terraform'
         command: 'plan'
         environmentServiceNameAzureRM: 'todo-sec-svc'
  